### ISSUE TITLE
Possible crash in AudioClip

### ISSUE THREAD

**Issue by dhleong** [dhleong/gakki#22]
Can't seem to reproduce it now, but this is what it looked like:

```
Error: RtApiCore::probeDeviceOpen: system error (kAudioHardwareIllegalOperationError) setting sample rate for device (1).
    at /Users/daniel/git/gakki/.shadow-cljs/builds/cli/dev/out/cljs-runtime/gakki/player/clip.cljs:70:18
    at Object.gakki$player$clip$from_stream [as from_stream] (/Users/daniel/git/gakki/.shadow-cljs/builds/cli/dev/out/cljs-runtime/gakki.player.clip.js:307:3)
    at gakki$player$track$core$create_clip (/Users/daniel/git/gakki/.shadow-cljs/builds/cli/dev/out/cljs-runtime/gakki/player/track/core.cljs:86:26)
    at /Users/daniel/git/gakki/.shadow-cljs/builds/cli/dev/out/cljs-runtime/cljs/core.cljs:4535:17
    at Function.cljs$core$IFn$_invoke$arity$2 (/Users/daniel/git/gakki/.shadow-cljs/builds/cli/dev/out/cljs-runtime/cljs.core.js:16149:3)
    at /Users/daniel/git/gakki/.shadow-cljs/builds/cli/dev/out/cljs-runtime/gakki/player/track/core.cljs:78:11
    at /Users/daniel/git/gakki/.shadow-cljs/builds/cli/dev/out/cljs-runtime/promesa/impl.cljc:86:30
```

My best guess is either 

1. Google returned a weird sample rate (though this seems unlikely) because when playing a track it crashed on previously I saw it start the download instead of playing from cache, or
2. Perhaps it's a sort of memory leak caused by how we create a new `RtAudio` instance for each track? IE: Maybe some CoreAudio APIs are colliding in some way

**Comment by dhleong** [comment]
Here's the new error as encountered with the extra logging:

```
 ERROR  Failed to initialize AudioClip RtApiCore::probeDeviceOpen: system error (kAudioHardwareIllegalOperationError) setting sample rate for device (1).
{:config
 {:duration 180660,
  :sample-rate 44100,
  :channels 2,
  :codec "mp4a",
  :container "mp4",
  :frame-size 960,
  :start-time-seconds 0}}

Error: RtApiCore::probeDeviceOpen: system error (kAudioHardwareIllegalOperationError) setting sample rate for device (1).
    at /Users/daniel/git/gakki/.shadow-cljs/builds/cli/dev/out/cljs-runtime/gakki/player/clip.cljs:73:20
    at Object.gakki$player$clip$from_stream [as from_stream] (/Users/daniel/git/gakki/.shadow-cljs/builds/cli/dev/out/cljs-runtime/gakki.player.clip.js:311:3)
    at gakki$player$track$core$create_clip (/Users/daniel/git/gakki/.shadow-cljs/builds/cli/dev/out/cljs-runtime/gakki/player/track/core.cljs:86:26)
    at /Users/daniel/git/gakki/.shadow-cljs/builds/cli/dev/out/cljs-runtime/cljs/core.cljs:4535:17
    at Function.cljs$core$IFn$_invoke$arity$2 (/Users/daniel/git/gakki/.shadow-cljs/builds/cli/dev/out/cljs-runtime/cljs.core.js:16149:3)
    at /Users/daniel/git/gakki/.shadow-cljs/builds/cli/dev/out/cljs-runtime/gakki/player/track/core.cljs:78:11
    at /Users/daniel/git/gakki/.shadow-cljs/builds/cli/dev/out/cljs-runtime/promesa/impl.cljc:86:30
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This time the file was cached, and the sample rate seems sane, so I'm leaning back toward the `RtAudio` issue I suggested above being the culprit.

EDIT: Strangely, I started a new process and tried to play the same track and it crashed in the same way...
EDIT2: OH the repro is literally that my headphones (apparently) only support `:sampleRates [16000 48000]`, and this file's sample rate doesn't match. It wasn't a 100% repro before because I wasn't using headphones. Maybe we can transcode to the correct sample rate?
