### ISSUE TITLE
Occasionally failing to fetch *any* URL for some YTM tracks

### ISSUE THREAD

**Issue by dhleong** [dhleong/gakki#30]
```
TypeError: Cannot read property 'Symbol(Request internals)' of null
    at isRequest (/Users/daniel/git/gakki/node_modules/node-fetch/lib/index.js:1158:50)
    at new Request (/Users/daniel/git/gakki/node_modules/node-fetch/lib/index.js:1180:8)
    at /Users/daniel/git/gakki/node_modules/node-fetch/lib/index.js:1409:19
    at new Promise (<anonymous>)
    at Object.fetch [as module$node_fetch] (/Users/daniel/git/gakki/node_modules/node-fetch/lib/index.js:1407:9)
    at /Users/daniel/git/gakki/.shadow-cljs/builds/cli/dev/out/cljs-runtime/gakki/accounts/ytm/playable.cljs:14:20
    at /Users/daniel/git/gakki/.shadow-cljs/builds/cli/dev/out/cljs-runtime/promesa/impl.cljc:86:30
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by dhleong** [comment]
Going to go ahead and close this. The changes linked above prevent a hard crash in this situation so we can gracefully continue to the next song on the queue. The real error is that apparently Youtube's API changed so ytdl-core is failing to generate any URLs. Hopefully they'll have a workaround soon, but in any case it's not an issue with our code.
